name: CI Terraform & Secret Scanning

on:
  push:
    branches: ["teste"]
  pull_request:
    branches: ["teste"]

env:
  TF_VERSION: "1.6.0"
  TF_WORKDIR: "environments/default"

jobs:
  # ------------------------------------------
  # 1) Verifica formatação e validação do Terraform
  # ------------------------------------------
  terraform-lint:
    name: "Terraform Format & Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform - fmt check
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform fmt -check -recursive

      - name: Terraform - validate
        working-directory: ${{ env.TF_WORKDIR }}
        run: |
          terraform init -input=false -backend=false
          terraform validate

  # ------------------------------------------
  # 2) Secret Scanning (truffleHog v3)
  # ------------------------------------------
  secret-scan:
    name: "Secret Scanning (truffleHog v3)"
    runs-on: ubuntu-latest
    needs: terraform-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Python e truffleHog v3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install trufflehog3

      - name: Executar truffleHog v3
        run: |
          trufflehog3 filesystem .

  # ------------------------------------------
  # 3) Deploy (terraform apply)
  #    Só roda se "terraform-lint" e "secret-scan" tiverem passado
  #    e apenas quando a branch for "main"
  # ------------------------------------------
  deploy:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: secret-scan
    # A condição abaixo faz com que o apply só execute em push para main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GCP credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "$HOME/gcp-key.json"
          gcloud auth activate-service-account --key-file="$HOME/gcp-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp-key.json"

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform apply -auto-approve
