name: CI Terraform

on:
  push:
    branches: ["teste", "master"]
  pull_request:
    branches: ["teste", "master"]

env:
  TF_VERSION: "1.6.0"
  TF_WORKDIR: "environments/default"

jobs:
  # ------------------------------------------
  # 1) Terraform Format & Validate (sempre em teste OU master)
  # ------------------------------------------
  terraform-lint:
    name: "Terraform Format & Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform - fmt check
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform fmt -check -recursive

      - name: Terraform - validate
        working-directory: ${{ env.TF_WORKDIR }}
        run: |
          terraform init -input=false -backend=false
          terraform validate

  # ------------------------------------------
  # 2) Deploy (terraform apply) — SOMENTE em master
  #    Este job só roda se o "terraform-lint" tiver passado e
  #    se for um push na branch master.
  # ------------------------------------------
  deploy:
    name: "Terraform Apply (só em master)"
    runs-on: ubuntu-latest
    needs: terraform-lint
    # Só executa em pushes na branch 'master'
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GCP credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "$HOME/gcp-key.json"
          gcloud auth activate-service-account --key-file="$HOME/gcp-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcp-key.json"

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform apply -auto-approve
