name: Secret Scanning (truffleHog)

on:
  push:
    branches: ["main", "teste"]
  pull_request:
    branches: ["main", "teste"]

jobs:
  trufflehog-scan:
    name: "Detectar segredos com truffleHog v3"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Python e truffleHog v3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade "attrs>=21.3.0"
          pip3 install trufflehog3

      - name: Executar truffleHog v3 (ignorando qualquer lockfile e pastas .terraform/)
        run: |
          trufflehog3 filesystem . \
            --exclude "**/.terraform.lock.hcl" \
            --exclude "**/.terraform/**"
