name: Secret Scanning (truffleHog)

# Dispara o CI em push ou pull request na branch 'main'
on:
  push:
    branches: ["TESTE"]
  pull_request:
    branches: ["TESTE"]

jobs:
  trufflehog-scan:
    name: "Detectar segredos com truffleHog"
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout do c贸digo (incluindo hist贸rico Git)
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

      # 2) Instala Python3 e o truffleHog via pip
      - name: Instalar Python e truffleHog
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install truffleHog

      # 3) Executa o truffleHog sobre todo o reposit贸rio
      - name: Executar truffleHog
        run: |
          trufflehog git .
